apiVersion: v2
name: docker
description: Docker-in-Kubernetes utilities
type: application
version: 0.1.0
appVersion: "24.0.0"
kubeVersion: ">=1.28.0-0"
home: https://github.com/cywf/helm-charts
sources:
  - https://github.com/cywf/helm-charts
  - https://github.com/docker/docker-ce
maintainers:
  - name: cywf
    url: https://github.com/cywf
keywords:
  - docker
  - container
  - utilities
